print("Ain't no sunshine when she's gone")
print("It's not warm when she's away")
print("Ain't no sunshine when she's gone")
print("And she's always gone too long")
print("Anytime she goes away")
print("")
print("Wonder this time where she's gone")
print("Wonder if she's gone to stay")
print("Ain't no sunshine when she's gone")
print("And this house just ain't no home")
print("Anytime she goes away")
print("")
for count in range(20):
    print("I know")

print("")
print("Hey, I oughta leave young thing alone")
print("But ain't no sunshine when she's gone")
print("")
print("Ain't no sunshine when she's gone")
print("Only darkness every day")
print("Ain't no sunshine when she's gone")
print("And this house just ain't no home")
for count in range(4):
    print("Anytime she goes away")
